name: TrithonEnv

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision
  - torchaudio
  - numpy=1.26.4
  - matplotlib=3.8.4
  - opencv
  - pillow=10.3.0
  - streamlit=1.35.0
  - pip

  - pip:
      - transformers==4.41.2
      - accelerate==0.31.0
      - sentencepiece==0.2.0
      - safetensors==0.4.3
      - huggingface_hub==0.23.5
      - pyaudio==0.2.14